image: node:lts

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm ci
    - npm run build
    - npm run export
    - mv out public   # GitLab Pages ต้องใช้โฟลเดอร์ชื่อ 'public'
  artifacts:
    paths:
      - public
  only:
    - main   # รันเมื่อ push บน branch main
